services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: pong
      POSTGRES_PASSWORD: pong
      POSTGRES_DB: pong
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pong"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: