name: Server Integration Test
on:
 pull_request:
   paths:
     - 'server/**'
jobs:
 integration-test:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     
     - name: Set up Python
       uses: actions/setup-python@v5
       with:
         python-version: '3.13'
         
     - name: Install websockets
       run: pip install websockets
       
     - name: Run docker compose
       run: |
         cd server
         docker compose up -d
         
     - name: Wait for services
       run: |
         timeout 30 bash -c 'while ! curl -s http://localhost:8000/health; do sleep 1; done'
         
     - name: Run integration tests  
       run: |
         cd server/tests
         python integration.py
         if [ $? -ne 0 ]; then
           echo "Integration tests failed"
           exit 1
         fi
         
     - name: Cleanup
       if: always()  
       run: |
         cd server
         docker compose down -v